spring.application.name=bentoflash

# MySQL Server Connection Setup
spring.datasource.url=jdbc:mysql://localhost:3306/bentoflashdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'none' because we are creating our database manually using schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keep SQL scripts running cleanly on startup
spring.sql.init.mode=never